---
title: "Feature Generation"
output: 
    html_document:
      theme: cerulean
      code_download: TRUE
      toc: TRUE
      toc_float:
        collapsed: FALSE
      toc_depth: 3
      code_folding: hide
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      tidy = TRUE, 
                      cache = FALSE,
                      warning = FALSE, 
                      message = FALSE,
                      eval = FALSE)
```

```{r}
library(fs)
library(here)
library(rio)

library(tidyverse)
library(magrittr)
library(dlookr)

library(quanteda)
library(quanteda.textstats)
library(quanteda.dictionaries)
library(udpipe)

theme_set(theme_bw())
```

## Data
```{r}
df <- dir_ls(here("data"), glob = "*.xlsx") %>% 
  map_dfr(., import, .id = "file") %>% 
  mutate(file = str_extract(file, "1a|1b|1c"),
         across(c(file:condition, gender, race), as.factor)
         ) %>% 
  rename(study = file) %>% 
  select(-gender, -race)

p_t_p <-
df %>% 
  select(study, p_right:t_right) %>% 
  gather(var, val, -study) %>% 
  ggplot(aes(val)) +
  geom_density() +
  facet_wrap(study ~ var)

d1 <-
df %>% 
  select(study:age) %>% 
  describe()

```

```{r, eval=TRUE}
load(here::here("R", "fet_gen2.RData"))

p_t_p

library(tidyverse)
library(knitr)
library(kableExtra)

d1 %>% 
  select(variable: kurtosis) %>% 
  kable(digits = 3) %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"),
                full_width = FALSE) %>% 
  row_spec(0, background = "gray", color = "white")
```


## Feature generation {.tabset .tabset-fade}
### Textual statistics with quanteda
```{r}
# tokenize
tokenized <- tokens(df$conflict_text,
                    remove_punct = FALSE,
                    remove_numbers = TRUE,
                    remove_symbols = TRUE,
                    remove_separators = TRUE)

# document-feature matrix
dm <- dfm(tokenized)

# basic statistics and entropy
text_stats <- textstat_summary(dm)

text_stats %<>% 
  mutate(chars = nchar(df$conflict_text),
         sents = nsentence(df$conflict_text),
         words = tokens - puncts,
         entropy = textstat_entropy(dm)$entropy) %>% 
  select(chars:puncts, words, entropy)

df <- bind_cols(df, text_stats)

# word length features
word_lengths <- map(tokenized, nchar)

df %<>% 
  mutate(wl_mean = map(word_lengths, mean),
         wl_median = map(word_lengths, median),
         wl_sd = map(word_lengths, sd),
         wl_min = map(word_lengths, min),
         wl_max = map(word_lengths, max))

# lexical diversity
ld <-
  textstat_lexdiv(dm,
                  remove_numbers = TRUE,
                  remove_punct   = TRUE,
                  remove_symbols = TRUE,
                  measure        = "all")

df <- bind_cols(df, ld[,-1])

# measures of readability
mor <-
  textstat_readability(df$conflict_text,
                       measure = "all")

df <- bind_cols(df, mor[,-1])

# features generated
d2 <-
df %>% 
  select(chars:81) %>% 
  describe()
```


```{r, eval=TRUE}
options(scipen = 10)

d2 %>% 
  select(variable: kurtosis) %>% 
  kable(digits = 3) %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"),
                full_width = FALSE) %>% 
  row_spec(0, background = "gray", color = "white") %>% 
  scroll_box(height = "750px",
             width = "850px")
```

### Text statistics via udpipe
```{r}
# udpipe_download_model(language = "english")
ud_eng <- udpipe_load_model(here("R", "english-ewt-ud-2.5-191206.udpipe"))

annotated <- udpipe_annotate(ud_eng, x = df$conflict_text)
annotated <- as.data.frame(annotated)
annotated <- cbind_morphological(annotated)

# part of speech tags
pos <-
annotated %>% 
  group_by(doc_id) %>% 
  count(upos) %>% 
  mutate(doc_id = parse_number(doc_id)) %>% 
  arrange(doc_id) %>% 
  pivot_wider(names_from = upos,
              values_from = n)

pos %<>% # replace NA with 0 since they are actually 0
  mutate(across(everything(), ~coalesce(., 0))
         )

df <- bind_cols(df, pos[,-1])

# xpos
xpos <-
annotated %>% 
  group_by(doc_id) %>% 
  count(xpos) %>% 
  mutate(doc_id = parse_number(doc_id)) %>% 
  arrange(doc_id) %>% 
  pivot_wider(names_from = xpos,
              values_from = n)

xpos %<>% # replace NA with 0 since they are actually 0
  mutate(across(everything(), ~coalesce(., 0))
         ) %>% 
  janitor::clean_names()

df <- bind_cols(df, xpos[,-1])

# morphological features
morphs <-
  annotated %>% 
  select(doc_id, starts_with("morph")) 

morph_freq <-
morphs %>% 
  pivot_longer(cols = -doc_id,
               names_to = "var",
               values_to = "val") %>% 
  group_by(doc_id, var) %>% 
  count(val) %>% 
  drop_na() %>% 
  pivot_wider(names_from = c(var, val),
              values_from = n) %>% 
  mutate(doc_id = parse_number(doc_id)) %>% 
  arrange(doc_id)

morph_freq %<>% # replace NA with 0 since they are actually 0
  mutate(across(everything(), ~coalesce(., 0))
         )

df <- bind_cols(df, morph_freq[,-1])

# syntactic relations
synts <-
  annotated %>% 
    group_by(doc_id) %>% 
    count(dep_rel) %>% 
    mutate(doc_id = parse_number(doc_id)) %>% 
    arrange(doc_id) %>% 
    pivot_wider(names_from = dep_rel,
                values_from = n) %>% 
  janitor::clean_names()

synts %<>% # replace NA with 0 since they are actually 0
  mutate(across(everything(), ~coalesce(., 0))
         )

df <- bind_cols(df, synts[,-1])

# features generated
names(pos[,-1])
names(xpos[,-1])
names(morph_freq[,-1])
names(synts[,-1])

d3 <- describe(pos[,-1])
d4 <- describe(xpos[,-1])
d5 <- describe(morph_freq[,-1])
d6 <- describe(synts[,-1])
```

```{r, eval=TRUE}
bind_rows(d3, d4, d5, d6) %>% 
  select(variable: kurtosis) %>% 
  kable(digits = 3) %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"),
                full_width = FALSE) %>% 
  row_spec(0, background = "gray", color = "white") %>% 
  scroll_box(height = "750px",
             width = "850px")
```


### Natural Language Proccessing
```{r}
embeddings <- import(here("data", "embeddings.csv"))

df <- bind_cols(df, embeddings)

# features generated
d7 <- describe(embeddings)
```

```{r, eval=TRUE}
d7 %>% 
  select(variable: kurtosis) %>% 
  kable(digits = 3) %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"),
                full_width = FALSE) %>% 
  row_spec(0, background = "gray", color = "white") %>% 
  scroll_box(height = "750px",
             width = "850px")
```


### Linguistic inquiry and word count (LIWC)
```{r}
liwc <- import(here("data", "liwc_df.csv")) %>% 
  mutate(across(file:condition, as.factor)) %>% 
  select(WC:OtherP)

df <- bind_cols(df, liwc)

# features generated
d8 <- describe(liwc[,-1:-4])
```

```{r, eval=TRUE}
d8 %>% 
  select(variable: kurtosis) %>% 
  kable(digits = 3) %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"),
                full_width = FALSE) %>% 
  row_spec(0, background = "gray", color = "white") %>% 
  scroll_box(height = "750px",
             width = "850px")
```


### Moral foundations dictionary
```{r}
mf <- liwcalike(df$conflict_text, 
                dictionary = data_dictionary_MFD) %>% 
  select(care.virtue:sanctity.vice)

df <- bind_cols(df, mf)

# features generated
d9 <- describe(mf)
```

```{r, eval=TRUE}
d9 %>% 
  select(variable: kurtosis) %>% 
  kable(digits = 3) %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"),
                full_width = FALSE) %>% 
  row_spec(0, background = "gray", color = "white")
```


```{r}
# export final dataset for modeling
# export(df, here("data", "df_final.csv"))
# save.image(here("R", "fet_gen.RData"))
```





